baseurl = "http://onlyangel.github.io/"
languageCode = "en-us"
title = "OnlyAngel Place"
description = "This is my hugo compiled blog"
contentdir = "content"
publishdir = "public"
builddrafts = false
canonifyurls = true
author = "Jose Angel Espinoza Portillo"

[indexes]
   category = "categories"
   tag = "tags"
[Params]
  AuthorName = "Jose Angel Espinoza Portillo"
  github = "onlyangel"
  twitter = "onlyangel"
  email = "jose@ngel.es"
  description = "This is my hugo compiled blog (params)"
  linkedin = "joseangelespinozaportillo"
[permalinks]
    post = "/:year/:month/:filename/"
    code = "/:filename/"


[Params.Header]

    name = "Jose Angel Espinoza Portillo"
    description = "Programador"
    email = "jose@ngel.es"
    image = "path/to/your/header/image"

[Params.Footer]

    [[Params.Footer.List]]

        icon_class = "twitter"
        icon_link = "https://www.twitter.com/onyangel"

    [[Params.Footer.List]]

        icon_class = "github"
        icon_link = "https://www.github.com/onlyangel"